version: '3.9'
services:
  app:
    container_name: nodejs-service
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - postgres
    
  postgres:
    container_name: postgres
    restart: always
    build: ./db/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres:
    name: postgres
    driver: bridge
